// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pdelta_binary_rd_cpp
NumericVector pdelta_binary_rd_cpp(double e, NumericVector a_c, NumericVector b_c, NumericVector a_t, NumericVector b_t);
RcppExport SEXP _adabay_pdelta_binary_rd_cpp(SEXP eSEXP, SEXP a_cSEXP, SEXP b_cSEXP, SEXP a_tSEXP, SEXP b_tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type e(eSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_c(a_cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b_c(b_cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_t(a_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b_t(b_tSEXP);
    rcpp_result_gen = Rcpp::wrap(pdelta_binary_rd_cpp(e, a_c, b_c, a_t, b_t));
    return rcpp_result_gen;
END_RCPP
}
// pdelta_binary_rr_cpp
NumericVector pdelta_binary_rr_cpp(double e, NumericVector a_c, NumericVector b_c, NumericVector a_t, NumericVector b_t);
RcppExport SEXP _adabay_pdelta_binary_rr_cpp(SEXP eSEXP, SEXP a_cSEXP, SEXP b_cSEXP, SEXP a_tSEXP, SEXP b_tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type e(eSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_c(a_cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b_c(b_cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_t(a_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b_t(b_tSEXP);
    rcpp_result_gen = Rcpp::wrap(pdelta_binary_rr_cpp(e, a_c, b_c, a_t, b_t));
    return rcpp_result_gen;
END_RCPP
}
// pdelta_binary_or_cpp
NumericVector pdelta_binary_or_cpp(double e, NumericVector a_c, NumericVector b_c, NumericVector a_t, NumericVector b_t);
RcppExport SEXP _adabay_pdelta_binary_or_cpp(SEXP eSEXP, SEXP a_cSEXP, SEXP b_cSEXP, SEXP a_tSEXP, SEXP b_tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type e(eSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_c(a_cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b_c(b_cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_t(a_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b_t(b_tSEXP);
    rcpp_result_gen = Rcpp::wrap(pdelta_binary_or_cpp(e, a_c, b_c, a_t, b_t));
    return rcpp_result_gen;
END_RCPP
}
// pdelta_gamma_rd_cpp
NumericVector pdelta_gamma_rd_cpp(double e, NumericVector a_c, NumericVector b_c, NumericVector a_t, NumericVector b_t);
RcppExport SEXP _adabay_pdelta_gamma_rd_cpp(SEXP eSEXP, SEXP a_cSEXP, SEXP b_cSEXP, SEXP a_tSEXP, SEXP b_tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type e(eSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_c(a_cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b_c(b_cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_t(a_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b_t(b_tSEXP);
    rcpp_result_gen = Rcpp::wrap(pdelta_gamma_rd_cpp(e, a_c, b_c, a_t, b_t));
    return rcpp_result_gen;
END_RCPP
}
// sim_tte_cpp
List sim_tte_cpp(int R, int n_pool_c, int n_pool_t, double lambda_c, double lambda_t, double rate_c, double rate_t, IntegerVector D_per_look);
RcppExport SEXP _adabay_sim_tte_cpp(SEXP RSEXP, SEXP n_pool_cSEXP, SEXP n_pool_tSEXP, SEXP lambda_cSEXP, SEXP lambda_tSEXP, SEXP rate_cSEXP, SEXP rate_tSEXP, SEXP D_per_lookSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    Rcpp::traits::input_parameter< int >::type n_pool_c(n_pool_cSEXP);
    Rcpp::traits::input_parameter< int >::type n_pool_t(n_pool_tSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_c(lambda_cSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_t(lambda_tSEXP);
    Rcpp::traits::input_parameter< double >::type rate_c(rate_cSEXP);
    Rcpp::traits::input_parameter< double >::type rate_t(rate_tSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type D_per_look(D_per_lookSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_tte_cpp(R, n_pool_c, n_pool_t, lambda_c, lambda_t, rate_c, rate_t, D_per_look));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_adabay_pdelta_binary_rd_cpp", (DL_FUNC) &_adabay_pdelta_binary_rd_cpp, 5},
    {"_adabay_pdelta_binary_rr_cpp", (DL_FUNC) &_adabay_pdelta_binary_rr_cpp, 5},
    {"_adabay_pdelta_binary_or_cpp", (DL_FUNC) &_adabay_pdelta_binary_or_cpp, 5},
    {"_adabay_pdelta_gamma_rd_cpp", (DL_FUNC) &_adabay_pdelta_gamma_rd_cpp, 5},
    {"_adabay_sim_tte_cpp", (DL_FUNC) &_adabay_sim_tte_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_adabay(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
