## Print, summary and plot methods for adabay S3 classes.
##
## Documentation note: each S3 method below is tagged with `@noRd` so that
## `devtools::document()` does NOT auto-generate a per-method Rd file. The
## help pages are instead written by hand and grouped per class in
## man/adabay_<class>-methods.Rd. The `@export` tags ensure that
## `roxygen2::roxygenise()` still registers the S3 methods in NAMESPACE
## via `S3method(generic, class)` directives. This is the standard pattern
## for packages that prefer hand-maintained, per-class grouped help pages
## over auto-generated per-method pages; the hand-maintained Rd files have
## no `% Generated by roxygen2` header and are therefore not touched by
## subsequent calls to `devtools::document()`.

#' @noRd
#' @export
print.adabay_design <- function(x, ...) {
  cat("Bayesian group sequential design\n")
  cat(sprintf("  Endpoint:        %s\n", x$endpoint))
  cat(sprintf("  Looks (n_looks): %d\n", x$n_looks))
  cat(sprintf("  Effect scale:    %s\n", x$effect_scale))
  cat(sprintf("  Alternative:     %s\n", x$alternative))
  cat(sprintf("  Null delta:      %g\n", x$delta_null))
  ar <- x$allocation_ratio %||% 1
  cat(sprintf("  Allocation (t:c): %g:1%s\n", ar,
              if (isTRUE(all.equal(ar, 1))) "  (balanced)" else ""))
  if (x$endpoint %in% c("continuous", "binary")) {
    cat(sprintf("  Cumulative n_c:  %s\n",
                paste(x$schedule$n_c, collapse = ", ")))
    cat(sprintf("  Cumulative n_t:  %s\n",
                paste(x$schedule$n_t, collapse = ", ")))
  } else if (x$endpoint == "count") {
    cat(sprintf("  Cumulative E_c:  %s\n",
                paste(x$schedule$E_c, collapse = ", ")))
    cat(sprintf("  Cumulative E_t:  %s\n",
                paste(x$schedule$E_t, collapse = ", ")))
  } else if (x$endpoint == "tte") {
    cat(sprintf("  Cumulative D_k:  %s\n",
                paste(x$schedule$D, collapse = ", ")))
    cat(sprintf("  Total events:    %d\n", x$schedule$D_total))
  }
  invisible(x)
}

#' @noRd
#' @export
print.adabay_prior <- function(x, ...) {
  cat("Bayesian group sequential prior\n")
  cat(sprintf("  Endpoint: %s\n", x$endpoint))
  for (a in c("c", "t")) {
    arm   <- x$arms[[a]]
    label <- if (a == "c") "Control" else "Treatment"
    cat(sprintf("  %s arm: family = %s, components = %d\n",
                label, arm$family, length(arm$components)))
    for (i in seq_along(arm$components)) {
      cat(sprintf("    [%d] weight = %.3f, %s\n", i, arm$weights[i],
                  paste(names(arm$components[[i]]),
                        unlist(arm$components[[i]]),
                        sep = " = ", collapse = ", ")))
    }
  }
  invisible(x)
}

#' @noRd
#' @export
print.adabay_decision <- function(x, ...) {
  cat("Bayesian group sequential decision rules\n")
  cat(sprintf("  Futility binding: %s\n", x$futility_binding))
  .print_rule <- function(rule, name) {
    if (length(rule$criteria) == 0L) {
      cat(sprintf("  %s: none\n", name))
      return(invisible(NULL))
    }
    if (isTRUE(rule$per_look)) {
      cat(sprintf("  %s (per-look):\n", name))
      for (k in seq_along(rule$criteria)) {
        cat(sprintf("    Look %d:\n", k))
        for (cr in rule$criteria[[k]])
          cat(sprintf("      threshold_effect = %g, threshold_prob = %.4f\n",
                      cr$threshold_effect, cr$threshold_prob))
      }
    } else {
      cat(sprintf("  %s (common across looks):\n", name))
      for (cr in rule$criteria)
        cat(sprintf("    threshold_effect = %g, threshold_prob = %.4f\n",
                    cr$threshold_effect, cr$threshold_prob))
    }
  }
  .print_rule(x$efficacy, "Efficacy")
  .print_rule(x$futility, "Futility")
  invisible(x)
}

#' @noRd
#' @export
print.adabay_accrual <- function(x, ...) {
  cat("Bayesian GSD accrual (recruitment / follow-up / dropout)\n")
  cat(sprintf("  Recruitment model: %s\n", x$model))
  if (!is.null(x$rate))
    cat(sprintf("  Rate:              %s\n", paste(x$rate, collapse = ", ")))
  if (is.numeric(x$follow_up))
    cat(sprintf("  Follow-up:         %g\n", x$follow_up))
  cat(sprintf("  Dropout:           %s\n", x$dropout))
  invisible(x)
}

#' @noRd
#' @export
print.adabay_oc <- function(x, ...) {
  binding <- isTRUE(x$decision$futility_binding)
  ## Uniform label column: 25-char label + 1 space separator + value.
  W <- 25L
  pad <- function(lbl) formatC(lbl, width = -W)
  cat("Operating characteristics\n")
  cat(sprintf("  %s %s\n", pad("Endpoint:"), x$design$endpoint))
  cat(sprintf("  %s %d\n", pad("Looks (n_looks):"), x$design$n_looks))
  cat(sprintf("  %s %s\n", pad("Futility:"),
              if (binding) "binding" else "non-binding"))
  ## Cumulative Type I error spent at each look = cumsum of the per-look
  ## efficacy crossings under the relevant convention (binding for
  ## futility_binding = TRUE, "as if futility absent" for non-binding).
  cum_alpha <- cumsum(if (binding) x$eff_prob_at_look
                      else x$alpha_at_look_nonbinding %||% x$eff_prob_at_look)
  fmt_vec <- function(v) paste(format(round(v, 4), nsmall = 4), collapse = ", ")
  cat(sprintf("  %s %.4f (if the null is specified)\n", pad("Type I error:"), x$alpha))
  cat(sprintf("  %s %s\n", pad("Cumulative Type I:"), fmt_vec(cum_alpha)))
  cat(sprintf("  %s %.4f\n", pad("Efficacy probability:"), x$eff_prob))
  cat(sprintf("  %s %s\n", pad("Stage efficacy:"), fmt_vec(x$eff_prob_at_look)))
  cat(sprintf("  %s %.4f\n", pad("Futility probability:"), x$fut_prob))
  cat(sprintf("  %s %s\n", pad("Stage futility:"), fmt_vec(x$fut_prob_at_look)))
  total_n <- switch(x$design$endpoint,
                    continuous = x$design$schedule$n_c[x$design$n_looks] +
                                 x$design$schedule$n_t[x$design$n_looks],
                    binary     = x$design$schedule$n_c[x$design$n_looks] +
                                 x$design$schedule$n_t[x$design$n_looks],
                    count      = x$design$schedule$E_c[x$design$n_looks] +
                                 x$design$schedule$E_t[x$design$n_looks],
                    tte        = x$design$schedule$D_total)
  total_n_label <- switch(x$design$endpoint,
                          continuous = "Planned total subjects:",
                          binary     = "Planned total subjects:",
                          count      = "Planned total exposure:",
                          tte        = "Planned total events:")
  expected_label <- switch(x$design$endpoint,
                           continuous = "Expected total subjects:",
                           binary     = "Expected total subjects:",
                           count      = "Expected total exposure:",
                           tte        = "Expected total events:")
  cat(sprintf("  %s %s\n", pad(total_n_label),
              if (is.numeric(total_n) && total_n == as.integer(total_n))
                format(as.integer(total_n)) else sprintf("%.1f", total_n)))
  cat(sprintf("  %s %.1f\n", pad(expected_label), x$expected_sample_size))
  if (!is.null(x$expected_duration) && !is.na(x$expected_duration))
    cat(sprintf("  %s %.2f\n", pad("Expected duration:"), x$expected_duration))
  if (!is.null(x$n_trials))
    cat(sprintf("  %s %d\n", pad("Virtual trials:"), x$n_trials))
  if (!is.null(x$seed))
    cat(sprintf("  %s %s\n", pad("Seed:"), format(x$seed)))
  if (!binding) {
    cat("Note: under non-binding futility, the Type I error is computed as if\n")
    cat("  futility were ignored (the standard convention for type I error\n")
    cat("  control), while stage efficacy and futility (and other operating\n")
    cat("  characteristics) still account for binding futility.\n")
  }
  invisible(x)
}

#' @noRd
#' @export
summary.adabay_oc <- function(object, ...) {
  list(
    alpha            = object$alpha,
    eff_prob         = object$eff_prob,
    fut_prob         = object$fut_prob,
    ess              = object$expected_sample_size,
    edur             = object$expected_duration,
    n_trials         = object$n_trials,
    eff_prob_at_look = object$eff_prob_at_look,
    fut_prob_at_look = object$fut_prob_at_look)
}

#' @noRd
#' @export
print.adabay_cache <- function(x, ...) {
  cat("Precomputed adabay_cache\n")
  cat(sprintf("  Endpoint:        %s\n", x$design$endpoint))
  cat(sprintf("  Looks (n_looks): %d\n", x$design$n_looks))
  cat(sprintf("  Virtual trials:  %d\n", x$n_trials))
  cat(sprintf("  Thresholds:      %s\n",
              paste(signif(x$thresholds, 4), collapse = ", ")))
  invisible(x)
}

## Per-look stopping-probability bar chart.
##
## Uses ggplot2 + theme_bw() and the ggsci BMJ colour palette when both are
## available; otherwise falls back to base graphics. When 'file' is
## supplied, the plot is also written to disk via ggsave; the file extension
## (jpeg/jpg/pdf/png) determines the device.
#' @noRd
#' @export
plot.adabay_oc <- function(x, file = NULL,
                        width = 7, height = 4, dpi = 300, ...) {
  n_looks <- x$design$n_looks
  if (!requireNamespace("ggplot2", quietly = TRUE)) {
    barplot(rbind(x$eff_prob_at_look, x$fut_prob_at_look),
            beside    = TRUE,
            names.arg = paste0("Look ", seq_len(n_looks)),
            col       = c("steelblue", "tomato"),
            ylab      = "Probability",
            main      = "Per-look stopping probabilities")
    legend("topleft", legend = c("Efficacy", "Futility"),
           fill = c("steelblue", "tomato"), bty = "n")
    return(invisible(NULL))
  }
  df <- data.frame(
    look = rep(seq_len(n_looks), 2L),
    type = factor(rep(c("Efficacy", "Futility"), each = n_looks),
                  levels = c("Efficacy", "Futility")),
    prob = c(x$eff_prob_at_look, x$fut_prob_at_look))
  p <- ggplot2::ggplot(df,
                       ggplot2::aes(x = factor(.data$look), y = .data$prob,
                                    fill = .data$type)) +
    ggplot2::geom_col(position = ggplot2::position_dodge(width = 0.8),
                      width = 0.7) +
    ggplot2::labs(x = "Look", y = "Stopping probability", fill = NULL) +
    ggplot2::theme_bw() +
    ggplot2::theme(legend.position = "top",
                   panel.grid.minor = ggplot2::element_blank())
  p <- p + .adabay_fill_bmj()
  if (!is.null(file)) {
    ggplot2::ggsave(filename = file, plot = p,
                    width = width, height = height, dpi = dpi, ...)
  }
  p
}

## Internal: BMJ palette, with graceful fallback when ggsci is unavailable.
.adabay_fill_bmj <- function() {
  if (requireNamespace("ggsci", quietly = TRUE)) {
    return(ggsci::scale_fill_bmj())
  }
  ggplot2::scale_fill_manual(values = c(Efficacy = "#2A6EBB",
                                        Futility = "#F0AB00"))
}
