# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pdelta_binary_rd_cpp <- function(e, a_c, b_c, a_t, b_t) {
    .Call(`_adabay_pdelta_binary_rd_cpp`, e, a_c, b_c, a_t, b_t)
}

pdelta_binary_rr_cpp <- function(e, a_c, b_c, a_t, b_t) {
    .Call(`_adabay_pdelta_binary_rr_cpp`, e, a_c, b_c, a_t, b_t)
}

pdelta_binary_or_cpp <- function(e, a_c, b_c, a_t, b_t) {
    .Call(`_adabay_pdelta_binary_or_cpp`, e, a_c, b_c, a_t, b_t)
}

pdelta_gamma_rd_cpp <- function(e, a_c, b_c, a_t, b_t) {
    .Call(`_adabay_pdelta_gamma_rd_cpp`, e, a_c, b_c, a_t, b_t)
}

sim_tte_cpp <- function(R, n_pool_c, n_pool_t, lambda_c, lambda_t, rate_c, rate_t, D_per_look) {
    .Call(`_adabay_sim_tte_cpp`, R, n_pool_c, n_pool_t, lambda_c, lambda_t, rate_c, rate_t, D_per_look)
}

